In [1]:
import os
import dotenv
from sqlalchemy import create_engine
import pandas as pd
dotenv.load_dotenv(override=True)
username = os.getenv("username")
password = os.getenv("password")
host = os.getenv("host")
dbname = os.getenv("dbname")
conn_string = f"mysql+pymysql://{username}:{password}@{host}/{dbname}"
db_engine = create_engine(conn_string)

query = "SELECT * FROM dimproduct"
df = pd.read_sql(query, db_engine)
db_engine.dispose ()
df.shape

#Estraiamo la tabella dimproduct dal database AdventureWorks, e valutiamo quanto segue: 
#• Quanti dati ci sono in totale? 
totali = df.shape[0]
print("Totali:", totali)

#• Quali sono i metadati? 
metadata = df.dtypes
print("Metadata:")
print(metadata)

#• Stampiamo il primo elemento 
first_element = df.iloc[0]
print(first_element)

#• Stampiamo l'ultimo elemento 
last_element = df.iloc[-1]
print(last_element)

#• Riusciamo a stampare cinque elementi a caso? 
elements = df.sample(5)
print(elements)

#• Quali sono i colori disponibili?
unique_colors = df['Color'].unique() 
print("Colore:", unique_colors)

Totali: 606
Metadata:
ProductKey                        int64
ProductAlternateKey              object
ProductSubcategoryKey           float64
WeightUnitMeasureCode            object
SizeUnitMeasureCode              object
EnglishProductName               object
SpanishProductName               object
FrenchProductName                object
StandardCost                    float64
FinishedGoodsFlag                 int64
Color                            object
SafetyStockLevel                  int64
ReorderPoint                      int64
ListPrice                       float64
Size                             object
SizeRange                        object
Weight                          float64
DaysToManufacture                 int64
ProductLine                      object
DealerPrice                     float64
Class                            object
Style                            object
ModelName                        object
LargePhoto                       object
EnglishDescription               object
FrenchDescription                object
ChineseDescription               object
ArabicDescription                object
HebrewDescription                object
ThaiDescription                  object
GermanDescription                object
JapaneseDescription              object
TurkishDescription               object
StartDate                datetime64[ns]
EndDate                  datetime64[ns]
Status                           object
dtype: object
ProductKey                                                               1
ProductAlternateKey                                                AR-5381
ProductSubcategoryKey                                                  NaN
WeightUnitMeasureCode                                                 None
SizeUnitMeasureCode                                                   None
EnglishProductName                                         Adjustable Race
SpanishProductName
FrenchProductName
StandardCost                                                           NaN
FinishedGoodsFlag                                                        0
Color                                                                   NA
SafetyStockLevel                                                      1000
ReorderPoint                                                           750
ListPrice                                                              NaN
Size                                                                  None
SizeRange                                                               NA
Weight                                                                 NaN
DaysToManufacture                                                        0
ProductLine                                                           None
DealerPrice                                                            NaN
Class                                                                 None
Style                                                                 None
ModelName                                                             None
LargePhoto               b'GIF89a\xf0\x00\x95\x00\xf7\x00\x00\x00\x00\x...
EnglishDescription                                                    None
FrenchDescription                                                     None
ChineseDescription                                                    None
ArabicDescription                                                     None
HebrewDescription                                                     None
ThaiDescription                                                       None
GermanDescription                                                     None
JapaneseDescription                                                   None
TurkishDescription                                                    None
StartDate                                              2003-07-01 00:00:00
EndDate                                                                NaT
Status                                                             Current
Name: 0, dtype: object
ProductKey                                                             606
ProductAlternateKey                                             BK-R19B-52
ProductSubcategoryKey                                                  2.0
WeightUnitMeasureCode                                                   LB
SizeUnitMeasureCode                                                     CM
EnglishProductName                                      Road-750 Black, 52
SpanishProductName                               Carretera: 750, negra, 52
FrenchProductName                               Vélo de route 750 noir, 52
StandardCost                                                        343.65
FinishedGoodsFlag                                                        1
Color                                                                Black
SafetyStockLevel                                                       100
ReorderPoint                                                            75
ListPrice                                                           539.99
Size                                                                    52
SizeRange                                                         48-52 CM
Weight                                                               20.42
DaysToManufacture                                                        4
ProductLine                                                              R
DealerPrice                                                        323.994
Class                                                                    L
Style                                                                    U
ModelName                                                         Road-750
LargePhoto               b'GIF89a\xf0\x00\x95\x00\xf7\x00\x00\x8avw\xf7...
EnglishDescription       Entry level adult bike; offers a comfortable r...
FrenchDescription        Vélo d'adulte d'entrée de gamme ; permet une c...
ChineseDescription                       入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。
ArabicDescription        إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...
HebrewDescription        אופני מבוגרים למתחילים; מציעים רכיבה נוחה "מחו...
ThaiDescription          จักรยานระดับเริ่มต้นสำหรับผู้ใหญ่ ให้ความสบายใ...
GermanDescription        Ein Erwachsenenrad für Einsteiger; bietet Komf...
JapaneseDescription      エントリー レベルに対応する、クロスカントリーにも街への買い物にも快適な、大人の自転車。ハブ...
TurkishDescription       "Başlangıç seviyesinde yetişkin bisikleti, kır...
StartDate                                              2013-07-01 00:00:00
EndDate                                                                NaT
Status                                                             Current
Name: 605, dtype: object
     ProductKey ProductAlternateKey  ProductSubcategoryKey  \
170         171             PA-187B                    NaN
449         450             LT-T990                   33.0
374         375          BK-R89B-48                    2.0
57           58             HN-1224                    NaN
309         310          BK-R93R-62                    2.0

    WeightUnitMeasureCode SizeUnitMeasureCode            EnglishProductName  \
170                  None                None                 Paint - Black
449                  None                None  Taillights - Battery-Powered
374                    LB                  CM            Road-250 Black, 48
57                   None                None                     Hex Nut 7
309                    LB                  CM              Road-150 Red, 62

            SpanishProductName            FrenchProductName  StandardCost  \
170                                                                   NaN
449                                                                  5.77
374  Carretera: 250, negra, 48   Vélo de route 250 noir, 48       1320.68
57                                                                    NaN
309   Carretera: 150, roja, 62  Vélo de route 150 rouge, 62       2171.29

     FinishedGoodsFlag  ...  \
170                  0  ...
449                  1  ...
374                  1  ...
57                   0  ...
309                  1  ...

                                    ChineseDescription  \
170                                               None
449                     价格适中的车灯，确保夜间骑乘安全 – 使用三节 AAA 电池
374                 铝合金车架确保骑乘轻快、稳固，可用于室内比赛或参加俱乐部的越野活动。
57                                                None
309  此自行车曾为赛车手夺冠立下汗马功劳。与 Adventure Works Cycles 专业赛...

                                     ArabicDescription  \
170                                               None
449  إضاءة ذات سعر منخفض للقيادة بشكل آمن ليلاً، تس...
374  يوفر الهيكل المصنوع من سبيكة ألومنيوم قيادة قو...
57                                                None
309  إنها الدراجة التي يقودها الفائزون بسباقات الدر...

                                     HebrewDescription  \
170                                               None
449  תאורה במחיר סביר לרכיבה לילית בטוחה – פועלת בא...
374  מסגרת מסגסוגת אלומיניום מספקת רכיבה קלה ומוצקה...
57                                                None
309  אופניים אלה משמשים את מנצחי התחרויות. לאופניים...

                                       ThaiDescription  \
170                                               None
449  ไฟราคาประหยัดสำหรับการขับขี่ยามค่ำคืนที่ปลอดภั...
374  เฟรมอลูมิเนียมอัลลอยด์ ให้การขับขี่ที่เบา มั่น...
57                                                None
309  จักรยานคู่ใจของนักแข่งระดับแชมเปี้ยน  ได้รับกา...

                                     GermanDescription  \
170                                               None
449  Kostengünstiges Licht für sicheres Fahren bei ...
374  Der Rahmen aus Aluminiumlegierung bietet leich...
57                                                None
309  "Dieses Fahrrad wird von Rennprofis gefahren. ...

                                   JapaneseDescription  \
170                                               None
449             安全な夜間走行をサポートする低価格のライト (単 4 電池を 3 つ使用)。
374  レース トラックの走行でもオフロードのツーリングでも、アルミニウム合金のフレームにより、軽さ...
57                                                None
309  レース ウィナーも愛用する機種です。Adventure Works Cycles プロフェッ...

                                    TurkishDescription  StartDate    EndDate  \
170                                               None 2003-07-01        NaT
449  "Güvenli gece sürüşü için ekonomik far, 3 adet... 2012-07-01 2008-12-27
374  "Alüminyum alaşımı kadro, ister velodromda yar... 2012-07-01 2008-12-27
57                                                None 2003-07-01        NaT
309  "Bu bisiklet yarışçılar tarafından kullanılmak... 2011-07-01 2007-12-28

      Status
170  Current
449     None
374     None
57   Current
309     None

[5 rows x 36 columns]
Colore: ['NA' 'Black' 'Silver' 'Red' 'White' 'Blue' 'Multi' 'Yellow' 'Grey'
 'Silver/Black']

In [53]:
import os
import dotenv
from sqlalchemy import create_engine
import pandas as pd
dotenv.load_dotenv(override=True)
username = os.getenv("username")
password = os.getenv("password")
host = os.getenv("host")
dbname = os.getenv("dbname")
conn_string = f"mysql+pymysql://{username}:{password}@{host}/{dbname}"
db_engine = create_engine(conn_string)

query = "SELECT * FROM dimproduct"
df = pd.read_sql(query, db_engine)
db_engine.dispose ()
df.shape

#In media quanto pesano i prodotti? 
Peso_medio = round(df['Weight'].mean(),2)
print("Peso medio:", Peso_medio)

#• Quanto pesa il più leggero? 
Leggero = df['Weight'].min()
print("Peso più leggero:", Leggero)

#• Quanto pesa il più pesante? 
Leggero = df['Weight'].max()
print("Peso più leggero:", Leggero)

#• Quanti prodotti pesano più di 100 Kg? 
Leggero = df[df['Weight'] > 100][['EnglishProductName', 'Weight']]
print(Leggero.to_string(index=False))

#• Quanto costano in media i prodotti (colonna DealerPrice)? 
Costo_medio = df['ListPrice'].mean ()
print("il costo medio è: ", round(Costo_medio,2))

#• Se prendiamo un quarto di tutti i prodotti, in modo che siano i più costosi, quale sarà il loro range di prezzo?
quarto = df.sort_values(by='ListPrice', ascending=False)
totale = len(quarto)
top_quarto = quarto.head(int(totale / 4))
range_alto = top_quarto['ListPrice'].max()
range_basso = top_quarto['ListPrice'].min()
print("Prezzo tra:", range_alto, "e", range_basso)

Peso medio: 56.19
Peso più leggero: 2.12
Peso più leggero: 1050.0
 EnglishProductName  Weight
    LL Mountain Rim   435.0
    ML Mountain Rim   450.0
    HL Mountain Rim   400.0
        LL Road Rim   445.0
        ML Road Rim   450.0
        HL Road Rim   400.0
        Touring Rim   460.0
LL Road Front Wheel   900.0
ML Road Front Wheel   850.0
HL Road Front Wheel   650.0
 LL Road Rear Wheel  1050.0
 ML Road Rear Wheel  1000.0
 HL Road Rear Wheel   890.0
    Rear Derailleur   215.0
        Rear Brakes   317.0
  LL Mountain Pedal   218.0
  ML Mountain Pedal   215.0
  HL Mountain Pedal   185.0
      LL Road Pedal   189.0
      ML Road Pedal   168.0
      HL Road Pedal   149.0
       Front Brakes   317.0
        LL Crankset   600.0
        ML Crankset   635.0
        HL Crankset   575.0
  LL Bottom Bracket   223.0
  ML Bottom Bracket   168.0
  HL Bottom Bracket   170.0
il costo medio è:  747.66
Prezzo tra: 3578.27 e 742.35

In [11]:
#• Qual è il prezzo medio per i prodotti di colore blu? 
lista_prezzi = df['ListPrice']
Blue = df[df['Color'] == 'Blue']
media_prezzi_blu = Blue['ListPrice'].mean()
print("Prezzo medio per i prodotti di colore Blue:", round(media_prezzi_blu, 2))

#• Qual è il prezzo medio per i prodotti di colore rosso o nero? 
lista_prezzi = df['ListPrice']
Red_balck = df[(df['Color'] == 'Red') | (df['Color'] == 'Black')]

media_prezzi_red_black = Red_balck['ListPrice'].mean()
print("Prezzo medio per i prodotti di colore Red o Black:", round(media_prezzi_red_black, 2))

#• Qual è il prezzo massimo per i prodotti di taglia 42 e peso oltre i 10 Kg? 
specifiche = df[(df['Size'] == 42) & (df['Weight'] > 10)]
prezzo_max = specifiche['ListPrice'].max()
print("Il prezzo massimo per i prodotti di taglia 42 e peso oltre i 10 Kg è:", prezzo_max)

#• Qual è il nome inglese e il costo di produzione (StandardCost) di tutti i prodotti di taglia 42, peso oltre i 10 Kg e colore argento? 
specifiche = df[(df['Size'] == 42) & (df['Weight'] > 10) & (df['Color'] == 'argento')]
nome_inglese = specifiche['EnglishDescription']
costo_di_produzione = specifiche['StandardCost']
print(nome_inglese, costo_di_produzione)

#• Esaminiamo la differenza tra lo StandardCost e il DealerPrice degli ultimi 20 elementi del dataset: 
#c'è un pattern? C'è qualche elemento che non lo segue?

ultimi_20 = df.tail(20)
ultimi_20['Differenza'] = ultimi_20['StandardCost'] - ultimi_20['DealerPrice']
print("Differenza tra StandardCost e DealerPrice degli ultimi 20 elementi del dataset:" , ultimi_20[['StandardCost', 'DealerPrice', 'Differenza']])
pattern = ultimi_20['Differenza'].value_counts()
print("\nConteggio delle differenze:")
print(pattern)
if len(pattern) == 1:
    print("\nTutte le differenze sono uguali, quindi c'è un pattern.")
else:
    print("\nCi sono differenze diverse, quindi ci potrebbe essere qualche elemento che non segue il pattern.")

Prezzo medio per i prodotti di colore Blue: 860.1
Prezzo medio per i prodotti di colore Red o Black: 917.08
Il prezzo massimo per i prodotti di taglia 42 e peso oltre i 10 Kg è: nan
Series([], Name: EnglishDescription, dtype: object) Series([], Name: StandardCost, dtype: float64)
Differenza tra StandardCost e DealerPrice degli ultimi 20 elementi del dataset:      StandardCost  DealerPrice  Differenza
586        419.78      461.694     -41.914
587        419.78      461.694     -41.914
588        419.78      461.694     -41.914
589        419.78      461.694     -41.914
590        308.22      338.994     -30.774
591        308.22      338.994     -30.774
592        308.22      338.994     -30.774
593        308.22      338.994     -30.774
594        308.22      338.994     -30.774
595        294.58      323.994     -29.414
596        294.58      323.994     -29.414
597        294.58      323.994     -29.414
598        294.58      323.994     -29.414
599        294.58      323.994     -29.414
600         23.97       32.394      -8.424
601         44.95       60.744     -15.794
602         53.94       72.894     -18.954
603        343.65      323.994      19.656
604        343.65      323.994      19.656
605        343.65      323.994      19.656

Conteggio delle differenze:
Differenza
-30.774    5
-29.414    5
-41.914    4
 19.656    3
-8.424     1
-15.794    1
-18.954    1
Name: count, dtype: int64

Ci sono differenze diverse, quindi ci potrebbe essere qualche elemento che non segue il pattern.

C:\Users\acqua\AppData\Local\Temp\ipykernel_12704\1608868993.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ultimi_20['Differenza'] = ultimi_20['StandardCost'] - ultimi_20['DealerPrice']

In [24]:
## AMAZON CSV

import pandas as pd
pd.read_csv('amazon.csv')
ACSV = pd.read_csv('amazon.csv')

a = ACSV.shape #Valutiamo la dimensione del dataset
b = ACSV.sample (10) #Visualizziamo dieci righe a caso;
c = ACSV.columns #Osserviamo quali sono i nomi di colonna;
d = ['positive'] == ['negative'] #Il dataset è bilanciato, ovvero, il numero di recensioni positive è uguale a quello delle negative, oppure no?
print (a,b,c,d)

(20000, 2)                                               reviewText  Positive
6695   Organizes and allows me to vote comics just li...         1
14184  So worth $2.00 you can draw anything so fun!!!...         1
19785  good game if u play wait til I play. do not ha...         1
614    grandkids downloaded it so I havent tried it  ...         1
18995  I already paid for a data plan on my phone but...         1
15496  This is one of the must have apps for your Kin...         1
15370  I started with the free version but decided I ...         1
13423  This app is amazing for when it comes to learn...         1
556    This is the first Angry Birds I played and I w...         1
6319   I wanted to help my math but I thought this ap...         0 Index(['reviewText', 'Positive'], dtype='object') False

In [53]:
## DIABETES CSV

import pandas as pd
pd.read_csv('diabetes.csv')
DCSV = pd.read_csv('diabetes.csv')

a = DCSV.shape
b = DCSV.sample(5)  #Osserviamone le dimensioni e un'anteprima di cinque righe;
c = DCSV.dtypes #Prendiamoci un po' di tempo per dare un'occhiata ai metadati delle colonne;
d = DCSV.columns #Stampiamo dei descrittori statistici del dataset;
print (d)
media_bmi = DCSV['Body mass index (weight in kg/(height in m)^2)'].mean()
media_eta = DCSV['Age (years)'].max()
media_numero_gravidanze = DCSV['Number of times pregnant'].median()
print ('media_bmi :' ,media_bmi,'media_eta:' ,media_eta, 'media_numero_gravidanze: ', media_numero_gravidanze)

#Selezioniamo i dati relativi a diverse fasce di età: <20, 20-30, 30-40, 40-50, >50;
intervalli_eta = [0, 20, 30, 40, 50, float('inf')]  # [0, 20), [20, 30), [30, 40), [40, 50), [50, infinito)
etichette_eta = ['<20', '20-30', '30-40', '40-50', '>50']
DCSV['Fascia di età'] = pd.cut(DCSV['Age (years)'], bins=intervalli_eta, labels=etichette_eta)
dati_fasce_eta = DCSV.groupby('Fascia di età', observed=False).size()
print("Dati relativi a diverse fasce di età:" , dati_fasce_eta)

#Qual è la media della pressione sanguigna diastolica per le diverse fasce di età?
intervalli_eta = [0, 20, 30, 40, 50, float('inf')]  
etichette_eta = ['<20', '20-30', '30-40', '40-50', '>50']
DCSV['Fascia di età'] = pd.cut(DCSV['Age (years)'], bins=intervalli_eta, labels=etichette_eta)
media_pressione_per_fascia_eta = DCSV.groupby('Fascia di età', observed=False)['Diastolic blood pressure (mm Hg)'].mean().reset_index()
print("Media della pressione diastolica (mm Hg) per ogni fascia di età:")
print(media_pressione_per_fascia_eta)

#media di pressione per anno
DCSV_age = DCSV['Age (years)']
media_pressione_per__eta = DCSV.groupby(DCSV_age)['Diastolic blood pressure (mm Hg)'].mean()
print ("Età:", DCSV_age, "media_pressione: ", round(media_pressione_per__eta, 2))

Index(['Number of times pregnant',
       'Plasma glucose concentration a 2 hours in an oral glucose tolerance test',
       'Diastolic blood pressure (mm Hg)', 'Triceps skin fold thickness (mm)',
       '2-Hour serum insulin (mu U/ml)',
       'Body mass index (weight in kg/(height in m)^2)',
       'Diabetes pedigree function', 'Age (years)', 'Class variable'],
      dtype='object')
media_bmi : 31.992578124999998 media_eta: 81 media_numero_gravidanze:  3.0
Dati relativi a diverse fasce di età: Fascia di età
<20        0
20-30    417
30-40    157
40-50    113
>50       81
dtype: int64
Media della pressione diastolica (mm Hg) per ogni fascia di età:
  Fascia di età  Diastolic blood pressure (mm Hg)
0           <20                               NaN
1         20-30                         65.323741
2         30-40                         70.273885
3         40-50                         74.787611
4           >50                         78.382716
Età: 0      50
1      31
2      32
3      21
4      33
       ..
763    63
764    27
765    30
766    47
767    23
Name: Age (years), Length: 768, dtype: int64 media_pressione:  Age (years)
21    65.94
22    63.72
23    64.32
24    64.96
25    59.67
26    64.18
27    73.50
28    68.31
29    68.24
30    64.86
31    64.38
32    70.06
33    65.65
34    74.00
35    75.60
36    69.12
37    75.95
38    71.12
39    72.67
40    69.23
41    67.59
42    73.39
43    78.46
44    61.75
45    83.07
46    76.00
47    78.33
48    78.40
49    81.40
50    78.25
51    84.50
52    81.50
53    79.00
54    89.33
55    70.25
56    76.33
57    76.80
58    78.29
59    74.00
60    80.00
61    76.00
62    71.50
63    78.00
64    78.00
65    78.67
66    86.00
67    72.67
68    82.00
69    81.00
70    82.00
72     0.00
81    74.00
Name: Diastolic blood pressure (mm Hg), dtype: float64

In [65]:
import pandas as pd
pd.read_csv('insurance.csv')
ICSV = pd.read_csv('insurance.csv')

#Visualizziamone le dimensioni, un'anteprima, e osserviamo i nomi di colonna;
a = ICSV.shape
b = ICSV.columns
print (a,b)

#Quali sono le medie di charges rispetto a region? Ci sono differenze significative?
medie_spese_per_regione = ICSV.groupby('region')['charges'].mean().reset_index()
print("\nMedie delle spese (charges) rispetto alla regione:")
print(round(medie_spese_per_regione,2))
#E rispetto a smoker? E a sex?
medie_smsx_per_regione = ICSV.groupby(['sex', 'smoker']).size().unstack()
print(round(medie_smsx_per_regione,2))

#Quali sono i descrittori statistici di bmi? Quali sono minimo, media e massimo di charges rispetto ai diversi quartili dei valori di bmi?
desc_bmi = ICSV['bmi'].describe()
print(desc_bmi)
quartili_bmi = ICSV['bmi'].quantile([0.25, 0.5, 0.75])
min_media_max_charges_per_quartile_bmi = ICSV.groupby(pd.cut(ICSV['bmi'], quartili_bmi, include_lowest=True)).agg({'charges': ['min', 'mean', 'max']})
print(min_media_max_charges_per_quartile_bmi)

(1338, 7) Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

Medie delle spese (charges) rispetto alla regione:
      region   charges
0  northeast  13406.38
1  northwest  12417.58
2  southeast  14735.41
3  southwest  12346.94
smoker   no  yes
sex
female  547  115
male    517  159
count    1338.000000
mean       30.663397
std         6.098187
min        15.960000
25%        26.296250
50%        30.400000
75%        34.693750
max        53.130000
Name: bmi, dtype: float64
                              charges
                                  min          mean          max
bmi
(26.294999999999998, 30.4]  1131.5066  11407.831468  62592.87309
(30.4, 34.694]              1135.9407  14358.173081  60021.39897

C:\Users\acqua\AppData\Local\Temp\ipykernel_12704\2748713736.py:21: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  min_media_max_charges_per_quartile_bmi = ICSV.groupby(pd.cut(ICSV['bmi'], quartili_bmi, include_lowest=True)).agg({'charges': ['min', 'mean', 'max']})

In [101]:
import pandas as pd
pd.read_csv('pokemon.csv')
PCSV = pd.read_csv('pokemon.csv')

#Verifichiamo la dimensione, un'anteprima e osserviamo i nomi di colonna;
a = PCSV.shape
b = PCSV.columns
print (a,b)

#È verosimile che la prima colonna dovrebbe essere un indice? SI
#Confrontiamolo con l'indice messo automaticamente da Pandas: combaciano?
c = PCSV.index
c
d = PCSV ['#']
d
#Se no, settare la prima colonna come indice.
e = PCSV.set_index(PCSV.columns[0], inplace=True)

#Quali sono i Pokémon leggendari?
leggendari = PCSV[PCSV['Legendary'] == True]
Nome = PCSV ['Name']
print("I Pokémon leggendari sono:")
print(leggendari[['Name', 'Legendary']])

#E quali sono i leggendari di tipo 1 Grass?

leggendari_erba = PCSV[(PCSV['Legendary'] == True) & (PCSV['Type 1'] == 'Grass')]
Tipo = PCSV['Type 1']
Nome = PCSV ['Name']
print("I Pokémon leggendari sono:")
print(leggendari_erba[['Name', 'Type 1', 'Legendary']])

#E leggendari di tipo 1 Ice o Fire?
leggendari_ice_fire = PCSV[(PCSV['Legendary'] == True) & (PCSV['Type 1'] == 'Ice') & (PCSV['Type 1'] == 'Fire')]
Tipo = PCSV['Type 1']
Nome = PCSV ['Name']
print("I Pokémon leggendari sono:")
print(leggendari_ice_fire[['Name', 'Type 1', 'Legendary']])

# Ordiniamo il dataset per la colonna Name;
PCSV_ordinato = PCSV.sort_values(by='Name')

PCSV_ordinato

#Trasformiamo Name nell'indice;
f = PCSV.set_index('Name', inplace=True)
f

#Quali sono i Pokémon della prima generazione con attacco > 50 e HP < 60?
pokemon_prima_generazione = PCSV[(PCSV['Generation'] == 1) & (PCSV['Attack'] > 50) & (PCSV['HP'] < 60)]
print("I Pokémon della prima generazione con attacco > 50 e HP < 60 sono:")
print(pokemon_prima_generazione[['Type 1', 'Generation']])

(800, 13) Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')
I Pokémon leggendari sono:
                    Name  Legendary
#
144             Articuno       True
145               Zapdos       True
146              Moltres       True
150               Mewtwo       True
150  MewtwoMega Mewtwo X       True
..                   ...        ...
719              Diancie       True
719  DiancieMega Diancie       True
720  HoopaHoopa Confined       True
720   HoopaHoopa Unbound       True
721            Volcanion       True

[65 rows x 2 columns]
I Pokémon leggendari sono:
                  Name Type 1  Legendary
#
492  ShayminLand Forme  Grass       True
492   ShayminSky Forme  Grass       True
640           Virizion  Grass       True
I Pokémon leggendari sono:
Empty DataFrame
Columns: [Name, Type 1, Legendary]
Index: []
I Pokémon della prima generazione con attacco > 50 e HP < 60 sono:
              Type 1  Generation
Name
Charmander      Fire           1
Charmeleon      Fire           1
Wartortle      Water           1
Rattata       Normal           1
Raticate      Normal           1
Spearow       Normal           1
Ekans         Poison           1
Pikachu     Electric           1
Sandshrew     Ground           1
Nidoran♂      Poison           1
Paras            Bug           1
Diglett       Ground           1
Dugtrio       Ground           1
Psyduck        Water           1
Mankey      Fighting           1
Growlithe       Fire           1
Bellsprout     Grass           1
Geodude         Rock           1
Graveler        Rock           1
Ponyta          Fire           1
Magneton    Electric           1
Farfetch'd    Normal           1
Doduo         Normal           1
Shellder       Water           1
Cloyster       Water           1
Krabby         Water           1
Kingler        Water           1
Hitmonlee   Fighting           1
Hitmonchan  Fighting           1
Koffing       Poison           1
Seadra         Water           1
Goldeen        Water           1
Eevee         Normal           1
Kabuto          Rock           1
Dratini       Dragon           1